image: node:lts

stages:
  - deploy

pages:
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y rsync  # Install rsync
    - mkdir public
    - rsync -av --exclude='public' ./ public/
  artifacts:
    paths:
      - public
  only:
    - main
