image: node:lts

# Cache dependencies (if any)
cache:
  paths:
    - node_modules/

# Define stages
stages:
  - deploy

# Job to deploy the static website to GitLab Pages
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r * public  # Copy all files into the 'public' directory
  artifacts:
    paths:
      - public  # Specify the folder containing your website files
  only:
    - main  # Run this job only when changes are pushed to the 'main' branch
