image: node:lts

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - find . -maxdepth 1 -not -name public -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - main
